theme = "github_light"

[editor]
rulers = [80, 120]
mouse = true

[keys.normal]
y = "yank_main_selection_to_clipboard"
p = "paste_clipboard_before"
# Global search word under cursor
"@" = [
  "move_prev_word_start",
  "move_next_word_end",
  "search_selection",
  "global_search",
]
