theme = "classic"

[editor]
text-width = 100
mouse = true
cursorline = false
color-modes = true
true-color = true


[editor.soft-wrap]
enable = false
wrap-at-text-width = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.lsp]
auto-signature-help = false


[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name", "file-type"]
right = ["diagnostics", "selections", "position", "file-encoding"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]

y = "yank_main_selection_to_clipboard"
p = "paste_clipboard_before"
"$" = "goto_line_end"


[keys.normal.space]
"tab" = ":buffer-next"
"." = ":config-open"
s = ["move_prev_word_start", "move_next_word_end", "search_selection", "global_search"]
k = ":buffer-close"
l = ":reload"
