theme = "github_light"

[editor]
rulers = [80, 120]
mouse = true
cursorline = true
color-modes = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[keys.normal]
y = "yank_main_selection_to_clipboard"
p = "paste_clipboard_before"
# Global search word under cursor
"@" = [
  "move_prev_word_start",
  "move_next_word_end",
  "search_selection",
  "global_search",
]
