[[language]]
name = "elixir"
scope = "source.elixir"
injection-regex = "elixir"
file-types = ["ex", "exs", "heex"]
roots = ["mix.exs"]
auto-format = true
diagnostic-severity = "Hint"
comment-token = "#"
indent = {tab-width = 2, unit = " "}
language-server = {command = "elixir-ls"}


[[language]]
name = "yaml"
auto-format = true
scope = "source.yaml"
injection-regex = "yaml"
file-types = ["yaml", "yml"]
comment-token = "#"
indent = {tab-width = 2, unit = " "}
language-server = {command = "yaml-language-server"}

