[[language]]
name = "elixir"
scope = "source.elixir"
injection-regex = "elixir"
file-types = ["ex", "exs", "heex"]
roots = ["mix.exs"]
auto-format = true
diagnostic-severity = "Hint"
comment-token = "#"
indent = {tab-width = 2, unit = " "}
language-server = {command = "/Users/pedrogutierrez/Projects/elixir-ls/language_server.sh"}


[[language]]
name = "yaml"
auto-format = true
scope = "source.yaml"
injection-regex = "yaml"
file-types = ["yaml", "yml"]
comment-token = "#"
indent = {tab-width = 2, unit = " "}
language-server = {command = "yaml-language-server"}

[[language]]
name = "ruby"
auto-format = true
scope = "source.rb"
injection-regex = "rb"
file-types = ["rb", "rake"]
comment-token = "#"
indent = {tab-width = 2, unit = " "}
config = { solargraph = { diagnostics = true, formatting = true } }
# language-server = {command = "yaml-language-server"}
